### ISSUE TITLE
USER STORY: ANONYMOUS USER

### ISSUE THREAD

**Issue by fergal92** [broken-helix/happiness#125]
As an anonymous user, I can create a post, so that I don't have to create an account.

### Acceptance Criteria: 

* The website allows users to remain anonymous 
* The website allows anonymous users to create posts 

### Tasks:

- Allow all visitors to the site to interact with the site 
- All users have the ability to access the posts functionality 
- Build an input form to take data from all users
---

**Comment by broken-helix** [comment]
Anonymous features were removed. User have to be logged in.
